apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: stackrox-
spec:
  pipelineRef:
    name: stackrox
  taskRunTemplate:
    podTemplate:
      env:
      - name: DOCKER_CONFIG
        value: /tmp/.docker
      - name: HOME
        value: /tmp
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 0
        fsGroup: 0
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
  params:
  - name: builder-image
    # value: localhost:5001/stackrox/stackrox-tekton:latest
    value: quay.io/klape/stackrox-builder:latest-arm64
  - name: repo-url
    value: https://github.com/kylape/stackrox.git
  - name: revision
    value: master
  taskRunSpecs:
  - pipelineTaskName: deploy-stackrox
    serviceAccountName: admin
  - pipelineTaskName: build-image
    podTemplate:
      securityContext:
        runAsUser: 0
