apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: stackrox-collector-builder-
spec:
  timeout: 2h0m
  pipelineRef:
    name: stackrox-collector-builder
  params:
  - name: repo-url
    value: https://github.com/stackrox/collector.git
  - name: revision
    value: 3.22.0
  - name: builder-tag
    value: latest
  - name: registry
    value: kind-registry:5000
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
