apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: stackrox-
spec:
  pipelineRef:
    name: stackrox
  taskRunTemplate:
    podTemplate:
      env:
      - name: DOCKER_CONFIG
        value: /tmp/.docker
      - name: HOME
        value: /tmp
      - name: NPM_CONFIG_USERCONFIG      # Add these npm-specific vars
        value: /tmp/.npmrc
      - name: NPM_CONFIG_CACHE
        value: /tmp/.npm-cache  # Or use workspace if you want persistence
      - name: NPM_CONFIG_PREFIX
        value: /tmp/.npm-global
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 0
        fsGroup: 0
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
  params:
  - name: builder-image
    # value: localhost:5001/stackrox/stackrox-tekton:latest
    value: quay.io/klape/stackrox-builder:latest-arm64
  - name: repo-url
    value: https://github.com/stackrox/stackrox.git
  - name: revision
    value: vmvm
  taskRunSpecs:
  - pipelineTaskName: deploy-stackrox
    serviceAccountName: admin
  - pipelineTaskName: build-image
    podTemplate:
      securityContext:
        runAsUser: 0
