apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: setup-aws-credentials
  annotations:
    tekton.dev/tags: "cache,aws"
spec:
  description: |
    Sets up AWS credentials for S3/MinIO cache operations.
    Creates .aws/credentials and .aws/config files in the shared workspace.
  params:
  - name: AWS_ACCESS_KEY_ID
    description: AWS Access Key ID (minio username)
    default: minioadmin
  - name: AWS_SECRET_ACCESS_KEY
    description: AWS Secret Access Key (minio password)
    default: minioadmin
  - name: S3_URL
    description: URL to object storage
    default: http://minio:9000
  workspaces:
  - name: shared-data
  steps:
  - name: setup-aws-credentials
    image: alpine:latest
    script: |
      #!/bin/sh
      set -ex
      
      # Create AWS credentials directory
      mkdir -p $(workspaces.shared-data.path)/.aws
      
      # Create AWS credentials file
      cat > $(workspaces.shared-data.path)/.aws/credentials <<EOF
      [default]
      aws_access_key_id = $(params.AWS_ACCESS_KEY_ID)
      aws_secret_access_key = $(params.AWS_SECRET_ACCESS_KEY)
      EOF
      
      # Create AWS config file  
      cat > $(workspaces.shared-data.path)/.aws/config <<EOF
      [default]
      region = us-east-1
      s3 =
          signature_version = s3v4
          addressing_style = path
      EOF
      
      echo "AWS credentials configured for S3 endpoint: $(params.S3_URL)"