apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: stackrox-
spec:
  pipelineRef:
    name: stackrox
  podTemplate:
    env:
    - name: DOCKER_CONFIG
      value: /tmp/.docker
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 0
      fsGroup: 0
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  params:
  - name: builder-image
    # value: localhost:5001/stackrox/stackrox-builder:latest
    value: quay.io/klape/stackrox-builder:latest
  - name: repo-url
    value: https://github.com/kylape/stackrox.git
  - name: revision
    value: "forked-ci"
  taskRunSpecs:
  - pipelineTaskName: deploy-stackrox
    taskServiceAccountName: admin
