apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: fetch-cache
spec:
  description: |
    Fetches a cache object from object storage using the given cache key
    and bucket name.  The task assumes the content is in .tar.zst file format
    and will all unzip into one folder.
    This task is designed to work with the put-cache task.
  params:
  - name: HASHED_FILE_PATH
    description: Path to file in source repository to hash to compute cache key
    type: string
  - name: S3_URL
    description: URL to object storage.
    default: http://minio:9000
  - name: AWS_ACCESS_KEY_ID
    description: Also known as username (minio)
    default: minioadmin
  - name: AWS_SECRET_ACCESS_KEY
    description: Also known as passowrd (minio)
    default: minioadmin
  - name: BUCKET_NAME
    description: Name of bucket that stores the caches
  steps:
  - name: build-and-push
    image: quay.io/klape/stackrox-builder:7
    script: |
      #!/usr/bin/env bash
      set -x
      cache_key=$(params.BUCKET_NAME)-$(sha256sum $(workspaces.shared-data.path)/source/$(params.HASHED_FILE_PATH) | cut -f 1 -d ' ')
      mc alias set minio $(params.S3_URL) $(params.AWS_ACCESS_KEY_ID) $(params.AWS_SECRET_ACCESS_KEY)
      mc get minio/$(params.BUCKET_NAME)/$cache_key $cache_key.tar.zst
      if [[ "$?" == "0" ]]; then
        tar -xf $cache_key.tar.zst --zstd 
      fi
    workingDir: $(workspaces.shared-data.path)
  workspaces:
  - name: shared-data
