apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stackrox-builder
spec:
  description: Build the StackRox builder image using buildah for multi-arch (arm64, amd64)
  params:
  - name: STACKROX_BUILDER_TAG
    type: string
    description: Tag for the StackRox builder image
    default: latest
  - name: REGISTRY
    type: string
    description: Container registry
    default: kind-registry:5000
  workspaces:
  - name: source
    description: The workspace containing the source code
  steps:
  - name: build-stackrox-builder-multiarch
    image: quay.io/buildah/stable
    script: |
      #!/usr/bin/env bash
      set -ex
      cd $(workspaces.source.path)/source
      
      # Build for arm64 using base-arm.Dockerfile
      buildah build --platform linux/arm64 \
        -t $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG)-arm64 \
        -f base-arm.Dockerfile \
        .
      
      # Build for amd64 using base.Dockerfile
      buildah build --platform linux/amd64 \
        -t $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG)-amd64 \
        -f base.Dockerfile \
        .
      
      # Push individual arch images
      buildah push --tls-verify=false \
        $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG)-arm64
      buildah push --tls-verify=false \
        $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG)-amd64
      
      # Create and push manifest list
      buildah manifest create $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG)
      buildah manifest add $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG) \
        $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG)-arm64
      buildah manifest add $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG) \
        $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG)-amd64
      buildah manifest push --all --tls-verify=false \
        $(params.REGISTRY)/stackrox/stackrox-builder:$(params.STACKROX_BUILDER_TAG)
    securityContext:
      privileged: true