apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: collector-builder
spec:
  description: Build the collector builder image using buildah for multi-arch (arm64, amd64)
  params:
  - name: COLLECTOR_BUILDER_TAG
    type: string
    description: Tag for the collector builder image
    default: latest
  - name: REGISTRY
    type: string
    description: Container registry
    default: kind-registry:5000
  workspaces:
  - name: source
    description: The workspace containing the source code
  steps:
  - name: build-builder-multiarch
    image: quay.io/buildah/stable
    script: |
      #!/usr/bin/env bash
      set -ex
      cd $(workspaces.source.path)/source
      
      # Build for arm64
      buildah build --platform linux/arm64 \
        -t $(params.REGISTRY)/stackrox/collector-builder:$(params.COLLECTOR_BUILDER_TAG)-arm64 \
        -f builder/Dockerfile \
        builder
      
      # Push individual arch images
      buildah push --tls-verify=false \
        $(params.REGISTRY)/stackrox/collector-builder:$(params.COLLECTOR_BUILDER_TAG)-arm64
      
      # Create and push manifest list
      buildah manifest create $(params.REGISTRY)/stackrox/collector-builder:$(params.COLLECTOR_BUILDER_TAG)
      buildah manifest add $(params.REGISTRY)/stackrox/collector-builder:$(params.COLLECTOR_BUILDER_TAG) \
        $(params.REGISTRY)/stackrox/collector-builder:$(params.COLLECTOR_BUILDER_TAG)-arm64
      buildah manifest push --all --tls-verify=false \
        $(params.REGISTRY)/stackrox/collector-builder:$(params.COLLECTOR_BUILDER_TAG)
    securityContext:
      privileged: true
